export const courses = [
  {
    id: 1,
    sno: 1,
    courseCode: "CSE101",
    courseName: "Introduction to Computer Science",
    courseCoordinator: "Dr. John Doe",
    expertFaculty: "Dr. Jane Doe",
    courseDuration: "4 weeks",
    status: "running",
  },
  {
    id: 2,
    sno: 2,
    courseCode: "CSE102",
    courseName: "Data Structures and Algorithms",
    courseCoordinator: "Dr. John Doe",
    expertFaculty: "Dr. Jane Doe",
    courseDuration: "6 weeks",
    status: "completed",
  },
  {
    id: 3,
    sno: 3,
    courseCode: "CSE103",
    courseName: "Web Development",
    courseCoordinator: "Dr. John Doe",
    expertFaculty: "Dr. Jane Doe",
    courseDuration: "8 weeks",
    status: "upcoming",
  },
  {
    id: 4,
    sno: 4,
    courseCode: "CSE104",
    courseName: "Machine Learning",
    courseCoordinator: "Dr. John Doe",
    expertFaculty: "Dr. Jane Doe",
    courseDuration: "10 weeks",
    status: "upcoming",
  },
  {
    id: 5,
    sno: 5,
    courseCode: "CSE105",
    courseName: "Artificial Intelligence",
    courseCoordinator: "Dr. John Doe",
    expertFaculty: "Dr. Jane Doe",
    courseDuration: "12 weeks",
    status: "upcoming",
  },
  {
    id: 6,
    sno: 6,
    courseCode: "CSE106",
    courseName: "Database Systems",
    courseCoordinator: "Dr. John Doe",
    expertFaculty: "Dr. Jane Doe",
    courseDuration: "6 weeks",
    status: "upcoming",
  },
  {
    id: 7,
    sno: 7,
    courseCode: "CSE107",
    courseName: "Computer Networks",
    courseCoordinator: "Dr. John Doe",
    expertFaculty: "Dr. Jane Doe",
    courseDuration: "8 weeks",
    status: "upcoming",
  },
  {
    id: 8,
    sno: 8,
    courseCode: "CSE108",
    courseName: "Operating Systems",
    courseCoordinator: "Dr. John Doe",
    expertFaculty: "Dr. Jane Doe",
    courseDuration: "10 weeks",
    status: "upcoming",
  },
  {
    id: 9,
    sno: 9,
    courseCode: "CSE109",
    courseName: "Software Engineering",
    courseCoordinator: "Dr. John Doe",
    expertFaculty: "Dr. Jane Doe",
    courseDuration: "12 weeks",
    status: "upcoming",
  },
  {
    id: 10,
    sno: 10,
    courseCode: "CSE110",
    courseName: "Computer Graphics",
    courseCoordinator: "Dr. John Doe",
    expertFaculty: "Dr. Jane Doe",
    courseDuration: "6 weeks",
    status: "upcoming",
  },
];